services:
  lorewyld:
    image: lorewyld:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      LW__LOG: lorewyld=info
      LW__DB_PATH: /opt/lorewyld/etc/database.db
      LW__DB_MAX_CONNECTIONS: 10
      LW__JWT_KEY_PATH: /opt/lorewyld/etc/jwt_signing_key.bin
    volumes:
      - ./database.db:/opt/lorewyld/etc/database.db
      - ./jwt_signing_key.bin:/opt/lorewyld/etc/jwt_signing_key.bin
