// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The authoring field schema for a content category, as a JSON string the
/// Flutter form builder renders from. `"null"` for an unknown/unauthorable
/// category.
String fieldSchema({required String category}) =>
    RustLib.instance.api.crateApiAuthoringFieldSchema(category: category);

/// The skeleton record for a category, as a JSON string used to seed a new
/// authoring form. `"null"` for an unknown category.
String defaultRecord({required String category}) =>
    RustLib.instance.api.crateApiAuthoringDefaultRecord(category: category);

/// Validate authoring input (a JSON object of field values) against the
/// category's schema. Returns a JSON array of `{field, message}` errors —
/// `"[]"` means valid.
String validateRecord({required String category, required String inputJson}) =>
    RustLib.instance.api.crateApiAuthoringValidateRecord(
      category: category,
      inputJson: inputJson,
    );
