// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The fixed new-player guidance questionnaire, as a JSON string the quiz
/// UI renders from.
String guidanceQuestionnaire() =>
    RustLib.instance.api.crateApiGuidanceGuidanceQuestionnaire();

/// Rank candidate records against quiz answers. `answers_json` is a JSON
/// array of `{question, value}`; `candidates_json` is a JSON object of
/// `{classes, species, backgrounds}` record arrays (full records or
/// summaries). Returns a JSON `RecommendationSet`, or `"null"` on
/// malformed input.
String guidanceRecommend({
  required String answersJson,
  required String candidatesJson,
}) => RustLib.instance.api.crateApiGuidanceGuidanceRecommend(
  answersJson: answersJson,
  candidatesJson: candidatesJson,
);
