// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `map_bonuses`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// Derive all sheet stats from a JSON-serialized `CharacterSheet` (the
/// mobile app already produces this via `CharacterSheet.toJson()`). A
/// malformed payload yields a zeroed block rather than crashing the
/// offline UI.
DerivedStats deriveStats({required String sheetJson}) =>
    RustLib.instance.api.crateApiSheetDeriveStats(sheetJson: sheetJson);

/// Ability modifier for a raw score — used by the create wizard before a
/// full sheet object exists.
int abilityModifier({required int score}) =>
    RustLib.instance.api.crateApiSheetAbilityModifier(score: score);

/// Proficiency bonus for a level.
int proficiencyBonus({required int level}) =>
    RustLib.instance.api.crateApiSheetProficiencyBonus(level: level);

/// Everything the sheet UI derives from the raw scores, computed in one
/// call per edit.
class DerivedStats {
  final int proficiencyBonus;
  final List<NamedBonus> abilityModifiers;
  final List<NamedBonus> savingThrowBonuses;
  final List<NamedBonus> skillBonuses;
  final int initiative;
  final int passivePerception;

  const DerivedStats({
    required this.proficiencyBonus,
    required this.abilityModifiers,
    required this.savingThrowBonuses,
    required this.skillBonuses,
    required this.initiative,
    required this.passivePerception,
  });

  @override
  int get hashCode =>
      proficiencyBonus.hashCode ^
      abilityModifiers.hashCode ^
      savingThrowBonuses.hashCode ^
      skillBonuses.hashCode ^
      initiative.hashCode ^
      passivePerception.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DerivedStats &&
          runtimeType == other.runtimeType &&
          proficiencyBonus == other.proficiencyBonus &&
          abilityModifiers == other.abilityModifiers &&
          savingThrowBonuses == other.savingThrowBonuses &&
          skillBonuses == other.skillBonuses &&
          initiative == other.initiative &&
          passivePerception == other.passivePerception;
}

/// A named derived value (an ability, save, or skill) and its bonus.
class NamedBonus {
  final String name;
  final int bonus;

  const NamedBonus({required this.name, required this.bonus});

  @override
  int get hashCode => name.hashCode ^ bonus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NamedBonus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          bonus == other.bonus;
}
